# This is the stock Ubuntu Desktop casper configuration with NFSv4 options added.
export USERNAME="ubuntu"
export USERFULLNAME="Live session user"
export HOST="ubuntu"
export BUILD_SYSTEM="Ubuntu"
export NFSOPTS="vers=3,tcp"
