package side.pki.openssl.cli;

import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.Getter;

/**
 * <a href="https://docs.openssl.org/master/man1/openssl/">https://docs.openssl.org/master/man1/openssl/</a>
 */
@Getter
public enum OpenSslCommands {
    asn1parse,
    ca,
    ciphers(CommandOptions.CiphersOptions.class),
    cms,
    crl,
    crl2pkcs7,
    dgst,
    dhparam,
    dsa,
    dsaparam,
    ec,
    ecparam,
    enc,
    engine,
    errstr,
    fipsinstall,
    gendsa,
    genpkey,
    genrsa,
    help,
    info,
    kdf,
    list,
    mac,
    nseq,
    ocsp,
    passwd,
    pkcs12,
    pkcs7,
    pkcs8,
    pkey,
    pkeyparam,
    pkeyutl,
    prime,
    rand,
    rehash,
    req,
    rsa,
    rsautl,
    s_client,
    s_server,
    s_time,
    sess_id,
    smime,
    speed,
    spkac,
    srp,
    storeutl,
    ts,
    verify,
    version,
    x509,
    blake2b512,
    blake2s256,
    md2,
    md4,
    md5,
    mdc2,
    rmd160,
    sha1,
    sha224,
    sha256,
    sha384,
    sha512,
    @JsonProperty("sha3-224")
    sha3_224,
    @JsonProperty("sha3-256")
    sha3_256,
    @JsonProperty("sha3-384")
    sha3_384,
    @JsonProperty("sha3-512")
    sha3_512,
    @JsonProperty("keccak-224")
    keccak_224,
    @JsonProperty("keccak-256")
    keccak_256,
    @JsonProperty("keccak-384")
    keccak_384,
    @JsonProperty("keccak-512")
    keccak_512,
    shake128,
    shake256,
    sm3,
    aes128,
    @JsonProperty("aes-128-cbc")
    aes_128_cbc,
    @JsonProperty("aes-128-cfb")
    aes_128_cfb,
    @JsonProperty("aes-128-ctr")
    aes_128_ctr,
    @JsonProperty("aes-128-ecb")
    aes_128_ecb,
    @JsonProperty("aes-128-ofb")
    aes_128_ofb,
    aes192,
    @JsonProperty("aes-192-cbc")
    aes_192_cbc,
    @JsonProperty("aes-192-cfb")
    aes_192_cfb,
    @JsonProperty("aes-192-ctr")
    aes_192_ctr,
    @JsonProperty("aes-192-ecb")
    aes_192_ecb,
    @JsonProperty("aes-192-ofb")
    aes_192_ofb,
    aes256,
    @JsonProperty("aes-256-cbc")
    aes_256_cbc,
    @JsonProperty("aes-256-cfb")
    aes_256_cfb,
    @JsonProperty("aes-256-ctr")
    aes_256_ctr,
    @JsonProperty("aes-256-ecb")
    aes_256_ecb,
    @JsonProperty("aes-256-ofb")
    aes_256_ofb,
    aria128,
    @JsonProperty("aria-128-cbc")
    aria_128_cbc,
    @JsonProperty("aria-128-cfb")
    aria_128_cfb,
    @JsonProperty("aria-128-ctr")
    aria_128_ctr,
    @JsonProperty("aria-128-ecb")
    aria_128_ecb,
    @JsonProperty("aria-128-ofb")
    aria_128_ofb,
    aria192,
    @JsonProperty("aria-192-cbc")
    aria_192_cbc,
    @JsonProperty("aria-192-cfb")
    aria_192_cfb,
    @JsonProperty("aria-192-ctr")
    aria_192_ctr,
    @JsonProperty("aria-192-ecb")
    aria_192_ecb,
    @JsonProperty("aria-192-ofb")
    aria_192_ofb,
    aria256,
    @JsonProperty("aria-256-cbc")
    aria_256_cbc,
    @JsonProperty("aria-256-cfb")
    aria_256_cfb,
    @JsonProperty("aria-256-ctr")
    aria_256_ctr,
    @JsonProperty("aria-256-ecb")
    aria_256_ecb,
    @JsonProperty("aria-256-ofb")
    aria_256_ofb,
    base64,
    bf,
    @JsonProperty("bf-cbc")
    bf_cbc,
    @JsonProperty("bf-cfb")
    bf_cfb,
    @JsonProperty("bf-ecb")
    bf_ecb,
    @JsonProperty("bf-ofb")
    bf_ofb,
    camellia128,
    @JsonProperty("camellia-128-cbc")
    camellia_128_cbc,
    @JsonProperty("camellia-128-cfb")
    camellia_128_cfb,
    @JsonProperty("camellia-128-ctr")
    camellia_128_ctr,
    @JsonProperty("camellia-128-ecb")
    camellia_128_ecb,
    @JsonProperty("camellia-128-ofb")
    camellia_128_ofb,
    camellia192,
    @JsonProperty("camellia-192-cbc")
    camellia_192_cbc,
    @JsonProperty("camellia-192-cfb")
    camellia_192_cfb,
    @JsonProperty("camellia-192-ctr")
    camellia_192_ctr,
    @JsonProperty("camellia-192-ecb")
    camellia_192_ecb,
    @JsonProperty("camellia-192-ofb")
    camellia_192_ofb,
    camellia256,
    @JsonProperty("camellia-256-cbc")
    camellia_256_cbc,
    @JsonProperty("camellia-256-cfb")
    camellia_256_cfb,
    @JsonProperty("camellia-256-ctr")
    camellia_256_ctr,
    @JsonProperty("camellia-256-ecb")
    camellia_256_ecb,
    @JsonProperty("camellia-256-ofb")
    camellia_256_ofb,
    cast,
    @JsonProperty("cast-cbc")
    cast_cbc,
    @JsonProperty("cast5-cbc")
    cast5_cbc,
    @JsonProperty("cast5-cfb")
    cast5_cfb,
    @JsonProperty("cast5-ecb")
    cast5_ecb,
    @JsonProperty("cast5-ofb")
    cast5_ofb,
    chacha20,
    des,
    @JsonProperty("des-cbc")
    des_cbc,
    @JsonProperty("des-cfb")
    des_cfb,
    @JsonProperty("des-ecb")
    des_ecb,
    @JsonProperty("des-ede")
    des_ede,
    @JsonProperty("des-ede-cbc")
    des_ede_cbc,
    @JsonProperty("des-ede-cfb")
    des_ede_cfb,
    @JsonProperty("des-ede-ofb")
    des_ede_ofb,
    @JsonProperty("des-ofb")
    des_ofb,
    des3,
    desx,
    @JsonProperty("des-ede3")
    des_ede3,
    @JsonProperty("des-ede3-cbc")
    des_ede3_cbc,
    @JsonProperty("des-ede3-cfb")
    des_ede3_cfb,
    @JsonProperty("des-ede3-ofb")
    des_ede3_ofb,
    idea,
    @JsonProperty("idea-cbc")
    idea_cbc,
    @JsonProperty("idea-cfb")
    idea_cfb,
    @JsonProperty("idea-ecb")
    idea_ecb,
    @JsonProperty("idea-ofb")
    idea_ofb,
    rc2,
    @JsonProperty("rc2-cbc")
    rc2_cbc,
    @JsonProperty("rc2-cfb")
    rc2_cfb,
    @JsonProperty("rc2-ecb")
    rc2_ecb,
    @JsonProperty("rc2-ofb")
    rc2_ofb,
    rc4,
    rc5,
    @JsonProperty("rc5-cbc")
    rc5_cbc,
    @JsonProperty("rc5-cfb")
    rc5_cfb,
    @JsonProperty("rc5-ecb")
    rc5_ecb,
    @JsonProperty("rc5-ofb")
    rc5_ofb,
    seed,
    @JsonProperty("seed-cbc")
    seed_cbc,
    @JsonProperty("seed-cfb")
    seed_cfb,
    @JsonProperty("seed-ecb")
    seed_ecb,
    @JsonProperty("seed-ofb")
    seed_ofb,
    sm4,
    @JsonProperty("sm4-cbc")
    sm4_cbc,
    @JsonProperty("sm4-cfb")
    sm4_cfb,
    @JsonProperty("sm4-ctr")
    sm4_ctr,
    @JsonProperty("sm4-ecb")
    sm4_ecb,
    @JsonProperty("sm4-ofb")
    sm4_ofb,
    ;

    private Class<? extends CommandOptions> commandOptions;

    OpenSslCommands() {
    }

    OpenSslCommands(Class<? extends CommandOptions> commandOptions) {
        this.commandOptions = commandOptions;
    }
}
