#!/usr/bin/sh

bb=/usr/bin/busybox

case "$1" in
deconfig)
    $bb ip addr flush dev "$interface"
    ;;
bound|renew)
    $bb ip addr flush dev "$interface"
    case "${mask:-255.255.255.0}" in
        [0-9]|[0-2][0-9]|3[0-2]) prefix=$mask ;;
        255.255.255.255) prefix=32 ;;
        255.255.255.0) prefix=24 ;;
        255.255.0.0) prefix=16 ;;
        255.0.0.0) prefix=8 ;;
        *) echo "deploy-image: unsupported DHCP netmask: $mask" >&2; exit 1 ;;
    esac
    $bb ip addr add "$ip/$prefix" dev "$interface"
    if [ -n "${router:-}" ]; then
        set -- $router
        $bb ip route replace default via "$1" dev "$interface"
    fi
    ;;
esac

exit 0
