package side.cloud.util.acme.lib.model;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import lombok.Data;
import lombok.experimental.Accessors;

import java.net.URI;
import java.util.Map;

/**
 * @see <a href=https://datatracker.ietf.org/doc/html/rfc7807>rfc 7807: Problem Details for HTTP APIs</a>
 */
@Dto
@Data
@Accessors(chain = true)
public class ProblemDetail {
    /**
     * A URI reference [RFC3986] that identifies the
     * problem type.  This specification encourages that, when
     * dereferenced, it provide human-readable documentation for the
     * problem type (e.g., using HTML [W3C.REC-html5-20141028]).  When
     * this member is not present, its value is assumed to be
     * "about:blank"
     */
    URI type;

    /**
     * A short, human-readable summary of the problem
     * type.  It SHOULD NOT change from occurrence to occurrence of the
     * problem, except for purposes of localization (e.g., using
     * proactive content negotiation; see [RFC7231], Section 3.4).
     */
    String title;

    /**
     * The HTTP status code ([RFC7231], Section 6)
     * generated by the origin server for this occurrence of the problem.
     */
    Integer status;

    /**
     * A human-readable explanation specific to this
     * occurrence of the problem.
     */
    String detail;

    /**
     * A URI reference that identifies the specific
     * occurrence of the problem.  It may or may not yield further
     * information if dereferenced.
     */
    URI instance;

    /**
     * <p>
     * Problem type definitions MAY extend the problem details object with
     * additional members.
     * </p>
     *
     * <p>
     * For example, our "out of credit" problem above defines two such
     * extensions -- "balance" and "accounts" to convey additional, problem-
     * specific information.
     * </p>
     *
     * <p>
     * Clients consuming problem details MUST ignore any such extensions
     * that they don't recognize; this allows problem types to evolve and
     * include additional information in the future.
     * </p>
     *
     * <p>
     * Note that because extensions are effectively put into a namespace by
     * the problem type, it is not possible to define new "standard" members
     * without defining a new media type.
     * </p>
     *
     * @see <a href=https://datatracker.ietf.org/doc/html/rfc7807#section-3.2>rfc7807 3.2: Extension Members</a>
     */
    @JsonAnyGetter
    @JsonAnySetter
    @JsonIgnore
    Map<String, Object> additionalProperties;
}
