services:
  db:
    image: postgres:16-alpine
    user: postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: auth_scratch_discord_client
    ports:
      - "127.0.0.1:5600:5432/tcp"
