apiVersion: jib/v1alpha1
kind: BuildFile

from:
  image: ubuntu:26.04@sha256:f3d28607ddd78734bb7f71f117f3c6706c666b8b76cbff7c9ff6e5718d46ff64
  platforms:
    - architecture: ${arch}
      os: linux

creationTime: 1970-01-01T00:00:01Z
format: Docker

entrypoint:
  - /main

layers:
  entries:
    - name: app
      files:
        - src: build/static-${arch}
          dest: /main
          properties:
            filePermissions: 755
