on:
  workflow_dispatch:
    # inputs:

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version: 1.26.3
          go-version-file: misc/scratch/learning/learning-building-go-applications/learning-go-application/go.mod
      - run: sudo apt-get update && sudo apt-get install -y gcc-x86-64-linux-gnu gcc-aarch64-linux-gnu
      - uses: docker/setup-docker-action@v5
      - uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          set -eux
          cd misc/scratch/learning/learning-building-go-applications/learning-go-application
          mkdir build
          touch build/docker-login # skip it

          # local bin
          local_bin="${HOME}/.local/bin"
          mkdir -p "${local_bin}"
          export PATH="${PATH}:${local_bin}"

          make docker-multiarch
