on:
  workflow_dispatch:
    inputs:
      SRC_USERNAME:
        required: true
        description: username to use for pulling base image
      SRC_PASSWORD:
        required: true
        description: password to use for pulling base image

permissions:
  contents: read
  packages: write

# gh: To use GitHub CLI in a GitHub Actions workflow, set the GH_TOKEN environment variable. Example:
env:
  GH_TOKEN: ${{ github.token }}

  SRC_USERNAME: ${{ inputs.SRC_USERNAME }}
  SRC_PASSWORD: ${{ inputs.SRC_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version: 1.26.3
          cache-dependency-path: misc/scratch/learning/learning-building-go-applications/learning-go-application/go.sum
      - run: sudo apt-get update && sudo apt-get install -y gcc-x86-64-linux-gnu gcc-aarch64-linux-gnu
      - uses: docker/setup-docker-action@v5
      - uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          set -eux
          cd misc/scratch/learning/learning-building-go-applications/learning-go-application
          mkdir build
          touch build/docker-login # skip it

          touch build/static-amd64 # 
          touch build/static-arm64 # temporarily skip it

          # local bin
          local_bin="${HOME}/.local/bin"
          mkdir -p "${local_bin}"
          export PATH="${PATH}:${local_bin}"

          GHCR_USER=${{ github.actor }} GHCR_PAT=${{ secrets.GITHUB_TOKEN }} \
            make docker-multiarch
